<header>
    <!-- -->
    <section class="banner-left">
        <a href="%home%"><img src="/assets/images/logos/logo.png" class="companyLogo" alt=""/></a>
        <a href="https://webetu.iutnc.univ-lorraine.fr/www/arnoux23u/crazycharlyday/produits" class="menu">Nos produits</a>
        <a href="https://webetu.iutnc.univ-lorraine.fr/www/arnoux23u/crazycharlyday/boites" class="menu">Nos boites</a>
    </section>
    <!-- -->
    <section class="banner-right">
        <a class="map" href="#"><img src="/assets/images/logosLanding/map-solid-24.png" alt=""/></a>
        <a class="user" href="https://webetu.iutnc.univ-lorraine.fr/www/arnoux23u/crazycharlyday/accounts/profile"><img src="/assets/images/logosLanding/user-solid-24.png"/></a>
        <a class="cart" href="#"><img src="/assets/images/logosLanding/cart-solid-24.png"/></a>
    </section>
    <!-- -->
</header>