<header>
    <!-- -->
    <section class="banner-left">
        <a href="landingPage.html"><img src="logo.png" class="companyLogo" alt=""/></a>
        <a href="" class="menu">Soin de corps</a>
        <a href="" class="menu">Accessoires</a>
        <a href="" class="menu">Art</a>
        <a href="" class="menu">Protections</a>
        <a href="" class="menu">Nos produits</a>
    </section>
    <!-- -->
    <section class="banner-right">
        <a class="map" href="landingPage.html"><img src="map-solid-24.png"/></a>
        <a class="user" href="landingPage.html"><img src="user-solid-24.png"/></a>
        <a class="cart" href="landingPage.html"><img src="cart-solid-24.png"/></a>
    </section>
    <!-- -->
</header>